language: ruby
rvm:
  - "2.3.1"
env:
  - DB=sqlite
script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rake db:test:prepare
  - bundle exec rake test test/
before_script:
  - echo "test:" >> config/secrets.yml
  - echo -n "  secret_key_base: " >> config/secrets.yml
  - bundle exec rake secret >> config/secrets.yml
  - echo -n "  secret_token: " >> config/secrets.yml
  - bundle exec rake secret >> config/secrets.yml
